# Generated by Django 4.0.3 on 2022-06-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_description_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
    ]
