# Generated by Django 4.0.3 on 2022-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_district_alter_profile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region_required',
            field=models.BooleanField(default=False),
        ),
    ]
