# Generated by Django 4.0.3 on 2022-07-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_region_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region_required',
        ),
    ]
